CREATE TABLE perfil
(
id CHAR(1) NOT NULL,
status VARCHAR(1),
marca VARCHAR(1),
data_inc DATE,
data_alt DATE,
data_hab DATE,
ocultar VARCHAR(1),
cadclifor VARCHAR(1),
clifor_i VARCHAR(1),
clifor_a VARCHAR(1),
clifor_e VARCHAR(1),
cadprof VARCHAR(1),
cadprof_i VARCHAR(1),
cadprof_a VARCHAR(1),
cadprof_e VARCHAR(1),
cadtransp VARCHAR(1),
cadtransp_i VARCHAR(1),
cadtransp_a VARCHAR(1),
cadtransp_e VARCHAR(1),
cadvendint VARCHAR(1),
cadvendint_i VARCHAR(1),
cadvendint_a VARCHAR(1),
cadvendint_e VARCHAR(1),
cadvendext VARCHAR(1),
cadvendext_i VARCHAR(1),
cadvendext_a VARCHAR(1),
cadvendext_e VARCHAR(1),
tabativ VARCHAR(1),
tabativ_i VARCHAR(1),
tabativ_a VARCHAR(1),
tabativ_e VARCHAR(1),
tabcateg VARCHAR(1),
tabcateg_i VARCHAR(1),
tabcateg_a VARCHAR(1),
tabcateg_e VARCHAR(1),
tabuf VARCHAR(1),
tabuf_i VARCHAR(1),
tabuf_a VARCHAR(1),
tabuf_e VARCHAR(1),
utcalc VARCHAR(1),
utcalend VARCHAR(1),
utblocnot VARCHAR(1),
utie VARCHAR(1),
utwe VARCHAR(1),
frusuario VARCHAR(1),
frusuario_i VARCHAR(1),
frusuario_a VARCHAR(1),
frusuario_e VARCHAR(1),
frperfil VARCHAR(1),
cadautor VARCHAR(1),
cadautor_i VARCHAR(1),
cadautor_a VARCHAR(1),
cadautor_e VARCHAR(1),
cadautoria VARCHAR(1),
cadautoria_i VARCHAR(1),
cadautoria_a VARCHAR(1),
cadautoria_e VARCHAR(1),
cadliv VARCHAR(1),
cadliv_i VARCHAR(1),
cadliv_a VARCHAR(1),
cadliv_e VARCHAR(1),
cadentliv VARCHAR(1),
cadentliv_i VARCHAR(1),
cadentliv_a VARCHAR(1),
cadentliv_e VARCHAR(1),
CONSTRAINT pk_perfil PRIMARY KEY (id)
);


