CREATE TABLE livros
(
ID VARCHAR(4) NOT NULL,
STATUS VARCHAR(1),
MARCA VARCHAR(1),
DATA_INC DATE,
DATA_ALT DATE,
DATA_HAB DATE,
TITULO VARCHAR(50),
ID_CATEG VARCHAR(2),
P_VENDA DECIMAL(8,2),
P_CUSTO DECIMAL(8,2),
BASE_CALC DECIMAL(8,2),
FORMATO VARCHAR(15),
NPAGINAS SMALLINT,
EDICAO SMALLINT,
ANO SMALLINT,
PESO DECIMAL(5,3),
LOC VARCHAR(10),
RESENHA BLOB SUB_TYPE 1,
CAPA BLOB SUB_TYPE 0,
PROMO CHAR(1),
EST_MIN INTEGER,
EST_DISP INTEGER,
QTDOAC INTEGER,
QTCONS INTEGER,
QTVEND INTEGER,
CONSTRAINT pk_livros primary key (id),
CONSTRAINT fk_Livros_Categ FOREIGN KEY (id_Categ) REFERENCES categ(id) ON UPDATE CASCADE
);
CREATE INDEX titulo_Livros ON livros(titulo);

