CREATE TABLE entLivros
(
ID INTEGER NOT NULL,
STATUS VARCHAR(1),
MARCA VARCHAR(1),
DATA_INC DATE,
DATA_ALT DATE,
DATA_HAB DATE,
ID_ISBN VARCHAR(4),
ID_FOR INTEGER,
NUMNOTA VARCHAR(6),
DATA_REC DATE,
QT_REC SMALLINT,
VALNOTA DECIMAL(8,2),
CONSTRAINT pk_EntLivros primary key (id)
);

