SET SQL DIALECT 3;

/* CREATE DATABASE 'C:\SCIVol1\database\DBSCI.GDB' PAGE_SIZE 4096

 DEFAULT CHARACTER SET  */
/* Domain definitions */
CREATE DOMAIN "D_BAIRRO" AS VARCHAR(25);
CREATE DOMAIN "D_CIDADE" AS VARCHAR(30);
CREATE DOMAIN "D_CODAGE" AS VARCHAR(6);
CREATE DOMAIN "D_CODBAN" AS VARCHAR(4);
CREATE DOMAIN "D_CPFCGC" AS VARCHAR(18);
CREATE DOMAIN "D_DDD" AS VARCHAR(3);
CREATE DOMAIN "D_EMAIL" AS VARCHAR(60);
CREATE DOMAIN "D_FANTASIA" AS VARCHAR(15);
CREATE DOMAIN "D_FONE" AS VARCHAR(9);
CREATE DOMAIN "D_MOEDA" AS DECIMAL(10, 2);
CREATE DOMAIN "D_NOMAGE" AS VARCHAR(30);
CREATE DOMAIN "D_NOMBAN" AS VARCHAR(30);
CREATE DOMAIN "D_NOME" AS VARCHAR(50);
CREATE DOMAIN "D_NOMERUA" AS VARCHAR(35);
CREATE DOMAIN "D_NUMCONTA" AS VARCHAR(10);
CREATE DOMAIN "D_NUMRUA" AS VARCHAR(25);
CREATE DOMAIN "D_RAMAL" AS VARCHAR(5);
CREATE DOMAIN "D_RGIE" AS VARCHAR(15);
CREATE DOMAIN "D_TIPRUA" AS VARCHAR(5);
CREATE DOMAIN "D_TITRUA" AS VARCHAR(7);

/* Table: ATIV, Owner: SYSDBA */

CREATE TABLE "ATIV" 
(
  "ID"	VARCHAR(2) NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "NOME"	VARCHAR(25) NOT NULL,
CONSTRAINT "PK_ATIV" PRIMARY KEY ("ID")
);

/* Table: AUTORIA, Owner: SYSDBA */

CREATE TABLE "AUTORIA" 
(
  "ID"	INTEGER NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "ID_AUTOR"	INTEGER NOT NULL,
  "ID_LIVRO"	VARCHAR(4) NOT NULL,
  "PDAUT_LIVRO"	DECIMAL(4, 2) NOT NULL,
  "PDAUT_AUTOR"	DECIMAL(4, 2) NOT NULL,
CONSTRAINT "PK_AUTORIA" PRIMARY KEY ("ID")
);

/* Table: CATEG, Owner: SYSDBA */

CREATE TABLE "CATEG" 
(
  "ID"	VARCHAR(2) NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "NOME"	VARCHAR(25) NOT NULL,
  "GRUPO"	VARCHAR(25) NOT NULL,
CONSTRAINT "PK_CATEG" PRIMARY KEY ("ID")
);

/* Table: CLIFOR, Owner: SYSDBA */

CREATE TABLE "CLIFOR" 
(
  "ID"	INTEGER NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "CF"	CHAR(1),
  "PFPJ"	CHAR(1),
  "DCTO"	DECIMAL(2, 0),
  "LIM_CRED"	DECIMAL(10, 2),
  "NOME"	"D_NOME" NOT NULL,
  "NOME_FANT"	VARCHAR(50),
  "TIPRUA"	"D_TIPRUA",
  "TITRUA"	"D_TITRUA",
  "NOMERUA"	"D_NOMERUA" NOT NULL,
  "NUMRUA"	"D_NUMRUA" NOT NULL,
  "BAIRRO"	"D_BAIRRO",
  "CIDADE"	"D_CIDADE" NOT NULL,
  "ID_UF"	VARCHAR(2) NOT NULL,
  "CEP"	VARCHAR(9) NOT NULL,
  "DDD"	"D_DDD",
  "TELEFONE"	"D_FONE",
  "RAMAL"	"D_RAMAL",
  "FAX"	"D_FONE",
  "CEL"	"D_FONE",
  "FANTASIA"	"D_FANTASIA",
  "CONTATO"	VARCHAR(30),
  "CPFCGC"	"D_CPFCGC",
  "RGIE"	"D_RGIE",
  "ID_VENDINT"	INTEGER,
  "ID_VENDEXT"	INTEGER,
  "PCPAG"	VARCHAR(30),
  "EMAIL"	"D_EMAIL",
  "BLEMAIL"	CHAR(1),
  "WWW"	VARCHAR(60),
  "ID_ATIV"	VARCHAR(2) NOT NULL,
  "COMPRA"	CHAR(1),
  "FORMA_PG"	VARCHAR(10),
  "FRETE"	CHAR(1),
  "ID_TRANSP"	INTEGER,
  "CODBANCO"	"D_CODBAN",
  "NOMBANCO"	"D_NOMBAN",
  "CODAGENCIA"	"D_CODAGE",
  "NOMAGENCIA"	"D_NOMAGE",
  "NUMCONTA"	"D_NUMCONTA",
CONSTRAINT "PK_CLIFOR" PRIMARY KEY ("ID")
);

/* Table: ENTLIVROS, Owner: SYSDBA */

CREATE TABLE "ENTLIVROS" 
(
  "ID"	INTEGER NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "ID_ISBN"	VARCHAR(4),
  "ID_FOR"	INTEGER,
  "NUMNOTA"	VARCHAR(6),
  "DATA_REC"	DATE,
  "QT_REC"	SMALLINT,
  "VALNOTA"	DECIMAL(8, 2),
CONSTRAINT "PK_ENTLIVROS" PRIMARY KEY ("ID")
);

/* Table: LIVROS, Owner: SYSDBA */

CREATE TABLE "LIVROS" 
(
  "ID"	VARCHAR(4) NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "TITULO"	VARCHAR(50),
  "ID_CATEG"	VARCHAR(2),
  "P_VENDA"	DECIMAL(8, 2),
  "P_CUSTO"	DECIMAL(8, 2),
  "BASE_CALC"	DECIMAL(8, 2),
  "FORMATO"	VARCHAR(15),
  "NPAGINAS"	SMALLINT,
  "EDICAO"	SMALLINT,
  "ANO"	SMALLINT,
  "PESO"	DECIMAL(5, 3),
  "LOC"	VARCHAR(10),
  "RESENHA"	BLOB SUB_TYPE TEXT SEGMENT SIZE 80,
  "CAPA"	BLOB SUB_TYPE 0 SEGMENT SIZE 80,
  "PROMO"	CHAR(1),
  "EST_MIN"	INTEGER,
  "EST_DISP"	INTEGER,
  "QTDOAC"	INTEGER,
  "QTCONS"	INTEGER,
  "QTVEND"	INTEGER,
CONSTRAINT "PK_LIVROS" PRIMARY KEY ("ID")
);

/* Table: LOCTRAB, Owner: SYSDBA */

CREATE TABLE "LOCTRAB" 
(
  "ID"	INTEGER NOT NULL,
  "ID_PRO"	INTEGER NOT NULL,
  "ID_ESC"	INTEGER NOT NULL,
CONSTRAINT "PK_LOCTRAB" PRIMARY KEY ("ID")
);

/* Table: PERFIL, Owner: SYSDBA */

CREATE TABLE "PERFIL" 
(
  "ID"	CHAR(1) NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "OCULTAR"	VARCHAR(1),
  "CADCLIFOR"	VARCHAR(1),
  "CLIFOR_I"	VARCHAR(1),
  "CLIFOR_A"	VARCHAR(1),
  "CLIFOR_E"	VARCHAR(1),
  "CADPROF"	VARCHAR(1),
  "CADPROF_I"	VARCHAR(1),
  "CADPROF_A"	VARCHAR(1),
  "CADPROF_E"	VARCHAR(1),
  "CADTRANSP"	VARCHAR(1),
  "CADTRANSP_I"	VARCHAR(1),
  "CADTRANSP_A"	VARCHAR(1),
  "CADTRANSP_E"	VARCHAR(1),
  "CADVENDINT"	VARCHAR(1),
  "CADVENDINT_I"	VARCHAR(1),
  "CADVENDINT_A"	VARCHAR(1),
  "CADVENDINT_E"	VARCHAR(1),
  "CADVENDEXT"	VARCHAR(1),
  "CADVENDEXT_I"	VARCHAR(1),
  "CADVENDEXT_A"	VARCHAR(1),
  "CADVENDEXT_E"	VARCHAR(1),
  "TABATIV"	VARCHAR(1),
  "TABATIV_I"	VARCHAR(1),
  "TABATIV_A"	VARCHAR(1),
  "TABATIV_E"	VARCHAR(1),
  "TABCATEG"	VARCHAR(1),
  "TABCATEG_I"	VARCHAR(1),
  "TABCATEG_A"	VARCHAR(1),
  "TABCATEG_E"	VARCHAR(1),
  "TABUF"	VARCHAR(1),
  "TABUF_I"	VARCHAR(1),
  "TABUF_A"	VARCHAR(1),
  "TABUF_E"	VARCHAR(1),
  "UTCALC"	VARCHAR(1),
  "UTCALEND"	VARCHAR(1),
  "UTBLOCNOT"	VARCHAR(1),
  "UTIE"	VARCHAR(1),
  "UTWE"	VARCHAR(1),
  "FRUSUARIO"	VARCHAR(1),
  "FRUSUARIO_I"	VARCHAR(1),
  "FRUSUARIO_A"	VARCHAR(1),
  "FRUSUARIO_E"	VARCHAR(1),
  "FRPERFIL"	VARCHAR(1),
  "CADAUTOR"	VARCHAR(1),
  "CADAUTOR_I"	VARCHAR(1),
  "CADAUTOR_A"	VARCHAR(1),
  "CADAUTOR_E"	VARCHAR(1),
  "CADAUTORIA"	VARCHAR(1),
  "CADAUTORIA_I"	VARCHAR(1),
  "CADAUTORIA_A"	VARCHAR(1),
  "CADAUTORIA_E"	VARCHAR(1),
  "CADLIV"	VARCHAR(1),
  "CADLIV_I"	VARCHAR(1),
  "CADLIV_A"	VARCHAR(1),
  "CADLIV_E"	VARCHAR(1),
  "CADENTLIV"	VARCHAR(1),
  "CADENTLIV_I"	VARCHAR(1),
  "CADENTLIV_A"	VARCHAR(1),
  "CADENTLIV_E"	VARCHAR(1),
  "DESCNIVEL"	VARCHAR(80),
CONSTRAINT "PK_PERFIL" PRIMARY KEY ("ID")
);

/* Table: TESTE, Owner: SYSDBA */

CREATE TABLE "TESTE" 
(
  "ID"	INTEGER NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "CAMPO_TESTE"	VARCHAR(30),
CONSTRAINT "PK_TESTE" PRIMARY KEY ("ID")
);

/* Table: TRANSP, Owner: SYSDBA */

CREATE TABLE "TRANSP" 
(
  "ID"	INTEGER NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "NOME"	"D_NOME" NOT NULL,
  "NOME_FANT"	VARCHAR(50),
  "TIPRUA"	"D_TIPRUA",
  "TITRUA"	"D_TITRUA",
  "NOMERUA"	"D_NOMERUA" NOT NULL,
  "NUMRUA"	"D_NUMRUA" NOT NULL,
  "BAIRRO"	"D_BAIRRO",
  "CIDADE"	"D_CIDADE" NOT NULL,
  "ID_UF"	VARCHAR(2) NOT NULL,
  "CEP"	VARCHAR(9) NOT NULL,
  "DDD"	"D_DDD",
  "TELEFONE"	"D_FONE",
  "RAMAL"	"D_RAMAL",
  "FAX"	"D_FONE",
  "CONTATO"	VARCHAR(30),
  "CGC"	"D_CPFCGC",
  "IE"	"D_RGIE",
  "EMAIL"	"D_EMAIL",
  "BLEMAIL"	CHAR(1),
  "WWW"	VARCHAR(60),
CONSTRAINT "PK_TRANSP" PRIMARY KEY ("ID")
);

/* Table: UF, Owner: SYSDBA */

CREATE TABLE "UF" 
(
  "ID"	VARCHAR(2) NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "NOMEST"	VARCHAR(25) NOT NULL,
  "REGIAO"	VARCHAR(15) NOT NULL,
  "ICM"	DECIMAL(2, 0) NOT NULL,
CONSTRAINT "PK_UF" PRIMARY KEY ("ID")
);

/* Table: USUARIO, Owner: SYSDBA */

CREATE TABLE "USUARIO" 
(
  "ID"	INTEGER NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "SENHA"	CHAR(7),
  "NOME"	VARCHAR(30),
  "FANTASIA"	VARCHAR(15),
  "DPTO"	VARCHAR(20),
  "NIVEL"	CHAR(1),
CONSTRAINT "PK_USUARIO" PRIMARY KEY ("ID")
);

/* Table: VENDEXT, Owner: SYSDBA */

CREATE TABLE "VENDEXT" 
(
  "ID"	INTEGER NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "NOME"	VARCHAR(15) NOT NULL,
  "DDD"	"D_DDD",
  "TELEFONE"	"D_FONE",
  "RAMAL"	"D_RAMAL",
  "CEL"	"D_FONE",
  "EMAIL"	"D_EMAIL",
  "COMIS"	DECIMAL(4, 2) NOT NULL,
CONSTRAINT "PK_VENDEXT" PRIMARY KEY ("ID")
);

/* Table: VENDINT, Owner: SYSDBA */

CREATE TABLE "VENDINT" 
(
  "ID"	INTEGER NOT NULL,
  "STATUS"	VARCHAR(1),
  "MARCA"	VARCHAR(1),
  "DATA_INC"	DATE,
  "DATA_ALT"	DATE,
  "DATA_HAB"	DATE,
  "NOME"	VARCHAR(15) NOT NULL,
  "DDD"	"D_DDD",
  "TELEFONE"	"D_FONE",
  "RAMAL"	"D_RAMAL",
  "CEL"	"D_FONE",
  "EMAIL"	"D_EMAIL",
  "COMIS"	DECIMAL(4, 2) NOT NULL,
CONSTRAINT "PK_VENDINT" PRIMARY KEY ("ID")
);

/*  Index definitions for all user tables */

CREATE INDEX "CEP_CLIFOR" ON "CLIFOR"("CEP");
CREATE INDEX "NOMERUA_CLIFOR" ON "CLIFOR"("NOMERUA");
CREATE INDEX "NOME_CLIFOR" ON "CLIFOR"("NOME");
CREATE INDEX "TITULO_LIVROS" ON "LIVROS"("TITULO");
CREATE INDEX "CEP_TRANSP" ON "TRANSP"("CEP");
CREATE INDEX "NOMERUA_TRANSP" ON "TRANSP"("NOMERUA");
CREATE INDEX "NOME_TRANSP" ON "TRANSP"("NOME");
ALTER TABLE "AUTORIA" ADD CONSTRAINT "FK_AUTORIA_CLIFOR" FOREIGN KEY ("ID_AUTOR") REFERENCES "CLIFOR" ("ID") ON UPDATE CASCADE;
ALTER TABLE "AUTORIA" ADD CONSTRAINT "FK_AUTORIA_LIVRO" FOREIGN KEY ("ID_LIVRO") REFERENCES "LIVROS" ("ID") ON UPDATE CASCADE;
ALTER TABLE "CLIFOR" ADD CONSTRAINT "FK_CLIFOR_ATIV" FOREIGN KEY ("ID_ATIV") REFERENCES "ATIV" ("ID") ON UPDATE CASCADE;
ALTER TABLE "CLIFOR" ADD CONSTRAINT "FK_CLIFOR_TRANSP" FOREIGN KEY ("ID_TRANSP") REFERENCES "TRANSP" ("ID") ON UPDATE CASCADE;
ALTER TABLE "CLIFOR" ADD CONSTRAINT "FK_CLIFOR_UF" FOREIGN KEY ("ID_UF") REFERENCES "UF" ("ID") ON UPDATE CASCADE;
ALTER TABLE "CLIFOR" ADD CONSTRAINT "FK_CLIFOR_VENDEXT" FOREIGN KEY ("ID_VENDEXT") REFERENCES "VENDEXT" ("ID") ON UPDATE CASCADE;
ALTER TABLE "CLIFOR" ADD CONSTRAINT "FK_CLIFOR_VENDINT" FOREIGN KEY ("ID_VENDINT") REFERENCES "VENDINT" ("ID") ON UPDATE CASCADE;
ALTER TABLE "ENTLIVROS" ADD CONSTRAINT "FK_ENTLIVROS_CLIFOR" FOREIGN KEY ("ID_FOR") REFERENCES "CLIFOR" ("ID");
ALTER TABLE "ENTLIVROS" ADD CONSTRAINT "FK_ENTLIVROS_LIVROS" FOREIGN KEY ("ID_ISBN") REFERENCES "LIVROS" ("ID") ON UPDATE CASCADE;
ALTER TABLE "LIVROS" ADD CONSTRAINT "FK_LIVROS_CATEG" FOREIGN KEY ("ID_CATEG") REFERENCES "CATEG" ("ID") ON UPDATE CASCADE;
ALTER TABLE "LOCTRAB" ADD CONSTRAINT "FK_CLIFOR_ID" FOREIGN KEY ("ID_PRO") REFERENCES "CLIFOR" ("ID");
ALTER TABLE "LOCTRAB" ADD CONSTRAINT "FK_CLIFOR_ID1" FOREIGN KEY ("ID_ESC") REFERENCES "CLIFOR" ("ID");
ALTER TABLE "TRANSP" ADD CONSTRAINT "FK_TRANSP_UF" FOREIGN KEY ("ID_UF") REFERENCES "UF" ("ID") ON UPDATE CASCADE;
ALTER TABLE "USUARIO" ADD CONSTRAINT "FK_USUARIO_PERFIL" FOREIGN KEY ("NIVEL") REFERENCES "PERFIL" ("ID");

CREATE GENERATOR "GEN_AUTORIA";
CREATE GENERATOR "GEN_CLIFOR";
CREATE GENERATOR "GEN_ENTLIVROS";
CREATE GENERATOR "GEN_LOCTRAB";
CREATE GENERATOR "GEN_TESTE";
CREATE GENERATOR "GEN_TRANSP";
CREATE GENERATOR "GEN_USUARIO";
CREATE GENERATOR "GEN_VENDEXT";
CREATE GENERATOR "GEN_VENDINT";

/* Grant Roles for this database */


/* Grant permissions for this database */

